<?php
//The template for displaying cs_article posts
//Direction from Erich: Make it look as much like the preview seen in CS1's search as possible with the addition of the original pub date being visible along side the new pub date generated by wordpress.

get_header();?>

    <div class="page-container">
        <div id="primary" class="content-area column large-8">
            <main id="main" class="site-main column large-12" role="main">

                <?php while (have_posts()): the_post();?>
			                <article id="post-<?php the_ID();?>" <?php post_class();?>>
			                    <header class="entry-header cs-ar-article-divider">
			                        <?php if (is_single()) {
        the_title('<h1 class="entry-title">', '</h1>');?>
			                        <p class="cs-ar-author">By:
			                            <?php echo get_the_author(); ?>
			                        </p>
			                        <p class="cs-ar-pub-date">
			                            <?php echo get_the_date(); ?>
			                        </p>
			                        <p class="cs-ar-original-pub-date">Original Publication Date:
			                            <?php $date = new DateTime(get_post_meta(get_the_ID(), 'original_publication_date', true));
        echo esc_attr($date->format('F j, Y'));?>
			                        </p>
			                        <?php if (has_excerpt(get_the_ID())) {
            the_excerpt();
        }

    } elseif (is_front_page() && is_home()) {
    the_title('<h3 class="entry-title"><a href="' . esc_url(get_permalink()) . '" rel="bookmark">', '</a></h3>');
} else {
    the_title('<h2 class="entry-title"><a href="' . esc_url(get_permalink()) . '" rel="bookmark">', '</a></h2>');
}?>
                    </header>

                    <?php if ('' !== get_the_post_thumbnail() && !is_single()): ?>
                    <div class="post-thumbnail">;
                        <a href="<?php the_permalink();?>">
                            <?php the_post_thumbnail('featured-image');?>
                        </a>
                    </div>
                    <?php endif;?>

                    <div class="entry-content">
                        <?php the_content(sprintf(
    __('Continue reading<span class="screen-reader-text"> "%s"</span>'),
    get_the_title()
));

wp_link_pages(array(
    'before' => '<div class="page-links">' . __('Pages:'),
    'after' => '</div>',
    'link_before' => '<span class="page-number">',
    'link_after' => '</span>',
));?>
                    </div>
                </article>
                <?php
// If comments are open or we have at least one comment, load up the comment template.
if (comments_open() || get_comments_number()):
    comments_template();
endif;

the_post_navigation(array(
    'prev_text' => '<span class="screen-reader-text">' . __('Previous Post: ') . '</span><span aria-hidden="true" class="nav-subtitle">' . __('Previous: ') . '</span> <span class="nav-title"><span class="nav-title-icon-wrapper"></span>%title</span>',
    'next_text' => '<span class="screen-reader-text">' . __('Next Post: ') . '</span><span aria-hidden="true" class="nav-subtitle">' . __('Next: ') . '</span> <span class="nav-title">%title<span class="nav-title-icon-wrapper"></span></span>',
));

endwhile; // End of the loop.
?>

            </main>
            <!-- #main -->
        </div>
        <!-- #primary -->
        <?php get_sidebar();?>
    </div>
    <!-- .wrap -->

    <?php get_footer();